version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Installing dependencies"
      - pip install paramiko

  build:
    commands:
      - echo "Running Python Program"
      - python main.py

      - echo "Compiling Java Program"
      - javac Main.java

      - echo "Running Java Program"
      - java Main

  post_build:
    commands:
      - echo "Deploying to EC2"
      - python deploy_to_ec2.py

artifacts:
  files:
    - '**/*'
