version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Installing dependencies"

  build:
    commands:
      - echo "Running Python Program"
      - python main.py

      - echo "Compiling Java Program"
      - javac Main.java

      - echo "Running Java Program"
      - java Main

artifacts:
  files:
    - '**/*'
